Scan Helm and Kubescape

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -69,21 +69,20 @@ jobs:
       # The default PostgreSQL port
         POSTGRES_PORT: 5432
 
-
     - name: Run Bandit security scanner
       run: bandit -r . -f sarif -o bandit-report.sarif || echo "BANDIT_FAIL=true" >> "$GITHUB_ENV"
-
+    
     - name: Upload Bandit scan results to Github Code Scanning
       uses: github/codeql-action/upload-sarif@v2
       with:
         sarif_file: bandit-report.sarif
 
     - name: Exit if Bandit fails
-      run: | 
-         if [ -n "$BANDIT_FAIL" ]; then
-            exit 1 
-         fi
-
+      run: |
+        if [ -n "$BANDIT_FAIL" ]; then
+          exit 1
+        fi
+          
   docker-build:
     needs: lint-and-test
     runs-on: ubuntu-latest
@@ -101,36 +100,34 @@ jobs:
         context: .
         load: true
         tags: ${{env.COMPONENT}}:latest
+    
     - name: Install Grype
       run: |
         curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
-
+    
     - name: Scan image with Grype
       run: |
-         grype ${{env.COMPONENT}}:latest --fail-on medium -o sarif > grype-report.sarif  || echo "GRYPE_FAIL=true" >> "$GITHUB_ENV"
+        grype ${{env.COMPONENT}}:latest --fail-on medium -o sarif > grype-report.sarif || echo "GRYPE_FAIL=true" >> "$GITHUB_ENV"
+
     
     - name: Upload Grype scan results to Github Code Scanning
       uses: github/codeql-action/upload-sarif@v2
       with:
         sarif_file: grype-report.sarif
+  
+  scan-helm:
+    needs: lint-and-test,docker-build
+    runs-on: ubuntu-latest
 
+    steps: 
+    - uses: kubescape/github-action@main
+      continue-on-error: true
+      with:
+        format: sarif
+        outputFile: kubescape-report
+        files: "chart/"
 
-
-  # Optional: Deploy to container registry
-  # Uncomment and configure as needed
-  # deploy:
-  #   needs: [lint-and-test, docker-build-and-scan, security-scan]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #   - name: Login to Docker Hub
-  #     uses: docker/login-action@v3
-  #     with:
-  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
-  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-  #   - name: Push to Docker Hub
-  #     uses: docker/build-push-action@v5
-  #     with:
-  #       push: true
-  #       tags: yourusername/user-management-api:latest
-
+    - name: Upload scan results to Github Code Scanning
+      uses: github/codeql-action/upload-sarif@v2
+      with:
+        sarif_file: kubescape-report.sarif   
